language: c

os:
  - linux

compiler:
  - gcc

branches:
  only:
    - master

before_install:
  - sudo apt-get install -y libxml2-dev libusb-1.0-0-dev autotools-dev automake libtool pkg-config gettext

before_script:
  - ./autogen.sh

script:
  - ./configure
  - make

env:
  global:
   - secure: "XRSSc+CVblNLncZCP1S9ffE2n3apun9LixLrXAxciSgpo/nFTKa7JqRLl109YSWA7FUfqOov4l812QUOrrN2z6sJ4m58SBx+jHYF3lhDtMGVuWYv0aSBITc5+IXw61hVAKon2gYeBPJ6vOA1b/IeSXGmx/dBu44AIr2wB5GOy6c="

addons:
  coverity_scan:
    project:
      name: "codestation/vitamtp"
      description: "Library to interact with Vita's USB MTP protocol"
    notification_email: codestation404@gmail.com
    build_command_prepend: "./autogen.sh ; ./configure"
    build_command: "make -j4"
    branch_pattern: coverity_scan
